### ISSUE TITLE
Instance for `Gen`

### ISSUE THREAD

**Issue by athanclark** [mvv/transformers-base#10]
I really like using `MonadBase` to claim which monad is at the bottom of a transformer stack. I often have to use stateful tricks when generating particular data in a timely fashion (for instance, unique lists) - making an abstract routine like:

```haskell
import Control.Monad
import Control.Monad.State
import Control.Monad.Base


newtype UniqueList a = UniqueList {unUniqueList :: [a]}

instance (Arbitrary a, Eq a) => UniqueList a where
  arbitrary = sized go
    where
      go s = runStateT (replicateM s go') []
      go' :: ( MonadBase Gen m
             , MonadState [a] m
             , Arbitrary a
             , Eq a
             ) => m a
      go' = do
        xs <- get
        x <- liftBase $ arbitrary `suchThat` (`notElem` xs)
        put $ x:xs
        return x
```

But, every place I want to do something like this, I need to add

```haskell
instance MonadBase Gen Gen where
  liftBase = id
```

Is there any competing reason not to do this?

**Comment by mvv** [comment]
Hi. You mean "not to do this in the library itself"? The main reason is to not arbitrarily add a large library as a dependency. You may try to convince folks to add the instance to the [quickcheck-instances](https://hackage.haskell.org/package/quickcheck-instances) package.
