### ISSUE TITLE
instance for ComposeT in mmorph package

### ISSUE THREAD

**Issue by infinity0** [mvv/transformers-base#12]
~~~~
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE UndecidableInstances #-}

import Control.Monad.Base (MonadBase(liftBase), liftBaseDefault)
import Control.Monad.Morph (MFunctor)
import Control.Monad.Trans (MonadTrans)
import Control.Monad.Trans.Compose (ComposeT)

instance (
    MonadBase b m,
    MFunctor f,
    MonadTrans f,
    MonadTrans g,
    Monad (f (g m))
  ) => MonadBase b (ComposeT f g m) where
    liftBase = liftBaseDefault
~~~~

I'm not sure if it's best to add this to this library or [mmorph](https://github.com/Gabriel439/Haskell-MMorph-Library/issues) - it would require one package to depend on the other (to be able to do the imports). Both packages already use all three of the language extensions that this requires. I arbitrarily decided to file the issue here, perhaps @Gabriel439 could comment further.

**Comment by RyanGlScott** [comment]
I like this idea, but I would suggest implementing the instance this way:

```haskell
instance MonadBase b (f (g m)) => MonadBase g (ComposeT f g m) where
    liftBase = ComposeT . liftBase
```

This requires far fewer constraints, and is more in-line with the other `ComposeT` instances which mention `m`.

**Comment by mvv** [comment]
I certainly won't be adding a dependency on `mmorph`, so I'm closing it.
