### ISSUE TITLE
MonadBase doesn't support ResourceT

### ISSUE THREAD

**Issue by nicuveo** [mvv/transformers-base#16]
It should be fairly straightforward to add it, except for the fact that -XSafe is enabled, and ResourceT does not meet that standard. I have started working on a pull request, but it will require disabling that feature...

**Comment by mvv** [comment]
It would be more appropriate to add the instance to the `resourcet` package.

**Comment by nicuveo** [comment]
Sorry to ping this again; @snoyberg neither wants to mark ResourceT as trustworthy, nor does he wants to add a dependency to tranformers-base. I'd understand if you didn't want, but what about dropping -XSafe and add the instance here instead?
